Allow opening multiple units in tabs
MegaMek/megameklab pull request #1673
Opened 2024-12-31 06:24 UTC by pavelbraginskiy

Many people have requested the ability to have many units open at once.

![image](https://github.com/user-attachments/assets/9103fb4e-a452-42ee-82de-dfb5d9f8b627)

Everything _seems_ to just work the way you might expect it to, but I'd like to get this to the testers to try to break it as soon as possible.

I haven't tested MHQ, because I don't know how to use MHQ. It _shouldn't_ break, as far as I can tell.

The one non-obvious feature is that you can shift-click the close-tab button to skip the "Would you like to save" dialog.

Future work: Allow opening all the units from a MUL file in tabs.

2025-01-01 12:36 UTC, pavelbraginskiy commented on megameklab/src/megameklab/ui/util/TabStateUtil.java
> +        clean.createNewFile();
This is fine: The presence of the `clean` file indicates that the rest of the process concluded without issue. If creating this file somehow fails, we just don't try to restore tabs next time.

2025-01-01 12:37 UTC, pavelbraginskiy commented on megameklab/src/megameklab/ui/util/TabStateUtil.java
> +            var fileName = parts[i + 1];
This can only happen with a malformed database, in which case crashing here would be the right thing to do.

2025-01-01 19:16 UTC, Sleet01 commented
@pavelbraginskiy Can you grab the `rs_font` entry from your `megameklab.properties` file?  I don't seem to have any fonts that support the "➕" and "❌" symbols.

2025-01-01 20:14 UTC, Sleet01 commented on megameklab/src/megameklab/ui/MegaMekLabTabbedUI.java
> +        // ...and save that size nad position on exit
"and"

2025-01-01 20:16 UTC, Sleet01 commented on megameklab/src/megameklab/ui/MegaMekLabTabbedUI.java
> +    private void restrictToScrenSize() {
"Screen"

2025-01-01 20:18 UTC, Sleet01 commented on megameklab/src/megameklab/ui/MegaMekLabTabbedUI.java
> +    //</editor-fold>
I don't think IDE-specific formatting comments should be included in the main repo.

2025-01-01 20:27 UTC, Sleet01 commented on megameklab/src/megameklab/ui/MegaMekLabTabbedUI.java
> +            var label = new JLabel("➕");
Request that you add:
```
            label.setFont(new Font("Symbola", Font.PLAIN, label.getFont().getSize()));
 ```
so that non-Windows users can see the symbols.

2025-01-01 20:27 UTC, Sleet01 commented on megameklab/src/megameklab/ui/MegaMekLabTabbedUI.java
> +            closeButton.setForeground(Color.RED);
Request that you add:
```
            closeButton.setFont(new Font("Symbola", Font.PLAIN, closeButton.getFont().getSize()));
 ```
so that non-Windows users can see the symbols.

2025-01-01 20:31 UTC, Sleet01 commented on megameklab/src/megameklab/ui/util/TabStateUtil.java
> +                    continue;
This definitely needs logging of the exception; no silent file errors.

2025-01-01 20:31 UTC, Sleet01 commented on megameklab/src/megameklab/ui/util/TabStateUtil.java
> +                    continue;
Same as above.

2025-01-01 20:39 UTC, Sleet01 commented on megameklab/src/megameklab/ui/util/TabStateUtil.java
> +            } catch (EntityLoadingException ignored) {}
We definitely want logging of exceptions while attempting to read unit files.

2025-01-01 20:40 UTC, Sleet01 commented on megameklab/src/megameklab/ui/util/TabStateUtil.java
> +                newFile.delete();
I'd argue that we shouldn't delete any files until we've completed all actions in the `try` block.

2025-01-01 20:49 UTC, Sleet01 requested changes
In addition to the stuff I commented on, I think we need to add the standard tab-related menu items and symantics:
- File -> Close, to mirror the X button function;
- File -> Open, similar to load but replaces the current tab's contents with the selected unit.
- Wrap the selected tab around instead of creating infinite new tabs, when using CTRL+Tab and right arrow in the tab bar.

Otherwise, this looks fantastic and I'm hyped to start using the tabs!

2025-01-02 00:02 UTC, Sleet01 approved these changes
Thanks, looks really good!

2025-01-02 02:31 UTC, merged